# Generated by Django 3.1.7 on 2021-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_auto_20210424_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.URLField(max_length=256, verbose_name='下載路徑'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=256, verbose_name='檔名'),
        ),
    ]
