# Generated by Django 3.1.7 on 2021-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('school', models.CharField(max_length=256)),
                ('contribute_context', models.CharField(max_length=256)),
            ],
        ),
    ]
