# Generated by Django 3.1.7 on 2021-04-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0002_auto_20210424_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, default='2021-04-24'),
        ),
        migrations.AlterField(
            model_name='case',
            name='scholorship_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(default='2021-04-24'),
        ),
        migrations.AlterField(
            model_name='case',
            name='total_money',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='visited_form',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='case',
            name='visited_photos',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
