# Generated by Django 3.1.7 on 2021-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0003_auto_20210424_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='scholorship_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
