# Generated by Django 3.1.7 on 2021-04-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0004_auto_20210424_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='contribute_context',
            field=models.TextField(max_length=256, verbose_name='資助項目'),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, default='2021-04-30', verbose_name='個案結束日期'),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_scholorship',
            field=models.BooleanField(default=False, verbose_name='獎學金'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=256, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='case',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='case',
            name='scholorship_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='獎學金金額'),
        ),
        migrations.AlterField(
            model_name='case',
            name='school',
            field=models.CharField(max_length=256, verbose_name='學校'),
        ),
        migrations.AlterField(
            model_name='case',
            name='situation',
            field=models.TextField(default='無', max_length=512, verbose_name='個案情況'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(default='2021-04-30', verbose_name='個案開始日期'),
        ),
        migrations.AlterField(
            model_name='case',
            name='total_money',
            field=models.IntegerField(default=0, null=True, verbose_name='目前總資助金額'),
        ),
        migrations.AlterField(
            model_name='case',
            name='visited_form',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='訪視表'),
        ),
        migrations.AlterField(
            model_name='case',
            name='visited_photos',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='訪視照片'),
        ),
    ]
