# Generated by Django 3.1.7 on 2021-05-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20210430_1228'),
        ('student_app', '0006_remove_student_case_id'),
        ('case_app', '0005_auto_20210430_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, default='2021-05-08', verbose_name='個案結束日期'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_student_name', to='student_app.student', verbose_name='學校'),
        ),
        migrations.AlterField(
            model_name='case',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_school', to='school_app.school', verbose_name='學校'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(default='2021-05-08', verbose_name='個案開始日期'),
        ),
    ]
