# Generated by Django 3.1.7 on 2021-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='case_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_end',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=256),
        ),
    ]
