# Generated by Django 3.1.7 on 2021-04-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0001_initial'),
        ('student_app', '0003_auto_20210423_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='case_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='case_student', to='case_app.case'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.TextField(max_length=256),
        ),
    ]
