# Generated by Django 3.1.7 on 2021-04-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20210430_1228'),
        ('case_app', '0005_auto_20210430_1207'),
        ('student_app', '0004_auto_20210423_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=256, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='case_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='case_student', to='case_app.case', verbose_name='個案編號'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='已結案'),
        ),
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.TextField(max_length=256, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=256, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='school_app.school', verbose_name='學校'),
        ),
    ]
