# Generated by Django 3.1.7 on 2021-05-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_auto_20210430_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='case_id',
        ),
    ]
