# Generated by Django 3.1.7 on 2021-05-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_student_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='content',
            field=models.CharField(default='無', max_length=256, verbose_name='資助內容'),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, default='2021-05-09', verbose_name='個案結束日期'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_scholorship',
            field=models.BooleanField(default=False, verbose_name='獎學金'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default='2021-05-09', verbose_name='個案開始日期'),
        ),
        migrations.AddField(
            model_name='student',
            name='visit_form',
            field=models.CharField(default='無', max_length=256, verbose_name='訪視表'),
        ),
        migrations.AddField(
            model_name='student',
            name='visit_photo',
            field=models.CharField(default='無', max_length=256, verbose_name='訪視照片'),
        ),
    ]
