# Generated by Django 3.1.7 on 2021-04-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20210424_0658'),
        ('student_app', '0004_auto_20210423_1446'),
        ('scholorship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholorship',
            name='datetime',
            field=models.DateField(default='2021-04-24'),
        ),
        migrations.AddField(
            model_name='scholorship',
            name='is_case',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scholorship',
            name='scholorship_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scholorship',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scho_school', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scho_student', to='student_app.student'),
        ),
    ]
