# Generated by Django 3.1.7 on 2021-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholorship_app', '0002_auto_20210424_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholorship',
            name='title',
            field=models.CharField(default='第一學期獎學金', max_length=256),
        ),
    ]
