# Generated by Django 3.1.7 on 2021-04-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20210430_1228'),
        ('student_app', '0004_auto_20210423_1446'),
        ('scholorship_app', '0004_auto_20210430_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholorship',
            name='datetime',
            field=models.DateField(default='2021-04-30', verbose_name='申請時間'),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='is_case',
            field=models.BooleanField(default=True, verbose_name='個案戶'),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scho_student', to='student_app.student', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='scholorship_amount',
            field=models.IntegerField(default=0, null=True, verbose_name='獎學金金額'),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scho_school', to='school_app.school', verbose_name='學校'),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='title',
            field=models.CharField(default='第一學期獎學金', max_length=256, verbose_name='申請名義'),
        ),
    ]
