# Generated by Django 3.1.7 on 2021-04-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateField(default='2021-04-24'),
        ),
        migrations.AddField(
            model_name='member',
            name='expired_at',
            field=models.DateField(default='2021-04-24'),
        ),
        migrations.AddField(
            model_name='member',
            name='intro_by',
            field=models.CharField(blank=True, default='無', max_length=256),
        ),
        migrations.AddField(
            model_name='member',
            name='is_donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_member_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(default='一般會員', max_length=256),
        ),
    ]
