# Generated by Django 3.1.7 on 2021-04-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0002_auto_20210424_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateField(default='2021-04-30'),
        ),
        migrations.AlterField(
            model_name='member',
            name='expired_at',
            field=models.DateField(default='2021-04-30'),
        ),
    ]
