# Generated by Django 3.1.7 on 2021-04-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='memo',
            field=models.TextField(max_length=512),
        ),
    ]
