# Generated by Django 3.1.7 on 2021-04-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0004_auto_20210423_1446'),
        ('member_app', '0002_auto_20210424_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('o', '支出'), ('i', '收入')], default='o', max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('amount', models.IntegerField(default=0)),
                ('dollor', models.CharField(default='NTD', max_length=256)),
                ('created_from', models.CharField(max_length=256)),
                ('created_at', models.DateField(blank=True, default='2021-04-24')),
                ('in_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fin_member', to='member_app.member')),
                ('out_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fin_student', to='student_app.student')),
            ],
        ),
    ]
