# Generated by Django 3.1.7 on 2021-04-23 07:22

from django.db import migrations, models
import finance_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', finance_app.models.EnumField(choices=[('o', 'Outcome'), ('i', 'Income')])),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('dollor', models.CharField(default='NTD', max_length=256)),
                ('created_from', models.CharField(max_length=256)),
            ],
        ),
    ]
