# Generated by Django 3.1.7 on 2021-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_remove_finance_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='title',
            field=models.CharField(default='日常支出', max_length=256),
        ),
    ]
