# Generated by Django 3.1.7 on 2021-04-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_finance_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='created_at',
            field=models.DateField(blank=True, default='2021-04-30'),
        ),
    ]
