# Generated by Django 3.1.7 on 2021-04-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0004_auto_20210430_1228'),
        ('student_app', '0004_auto_20210423_1446'),
        ('finance_app', '0004_auto_20210430_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='created_at',
            field=models.DateField(blank=True, default='2021-04-30', verbose_name='紀錄時間'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='created_from',
            field=models.CharField(max_length=256, verbose_name='經手人'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='dollor',
            field=models.CharField(default='NTD', max_length=256, verbose_name='幣別'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='in_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fin_member', to='member_app.member', verbose_name='收入對象'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='out_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fin_student', to='student_app.student', verbose_name='支出對象'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('o', '支出'), ('i', '收入')], default='o', max_length=256, verbose_name='收/支'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='title',
            field=models.CharField(default='日常支出', max_length=256, verbose_name='名目'),
        ),
    ]
